- name: Docker configure in Ec2 Machine
  hosts: managed
  become: true
  connection: ssh
  tasks:
    - name: Update the EC2 instance
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Deploy the Image and Run as Container
      command: docker run -itd -p 8084:8081 rajath06/insure-me1-app:4.0
